spring:
  thymeleaf:
    #关闭thymeleaf缓存
    cache: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seckill_demo?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    #spring自带的连接池(速度快)
    hikari:
      #连接池名称
      pool-name: DateHikariCP
      #最小空闲连接数
      minimum-idle: 5
      #空闲连接最大存活时间，默认600000(10分钟)
      idle-timeout: 1800000
      #连接最大存活时间，0表示永久存活，默认1800000(30分钟)
      max-lifetime: 1800000
      #最大连接数
      maximum-pool-size: 10
      #从连接池返回的连接自动提交
      auto-commit: true
      #连接超时时间，默认30000(30秒)
      connection-timeout: 30000
      #测试连接是否可用的查询语句
      connection-test-query: SELECT 1
  #redis配置
  redis:
    #服务器地址
    host: 192.168.6.100
    #端口号
    port: 6379
    #默认数据库
    database: 0
    #超时时间
    connect-timeout: 10000ms
    lettuce:
      pool:
        #最大连接数，默认8
        max-active: 8
        #最大连接阻塞等待时间，默认-1
        max-wait: 10000ms
        #最大空闲连接数，默认8
        max-idle: 200
        #最小空闲连接
        min-idle: 5


  # RabbitMQ 配置
  rabbitmq:
    # 服务器
    host: 192.168.6.100
    # 用户
    username: admin
    password: admin
    # 虚拟主机
    virtual-host: /
    # 端口
    port: 5672
    listener:
      simple:
        # 消费者最小数量
        concurrency: 10
        # 消费者最大数量
        max-concurrency: 10
        # 限制消费者每次只处理一条消息，处理完再继续下一条
        prefetch: 1
        # 默认启动时启动容器
        auto-startup: true
        # 当消息被拒绝时，重新进入队列
        default-requeue-rejected: true
    template:
      retry:
        # 发布重试，默认 false
        enabled: true
        # 重试时间 默认 1000 ms
        initial-interval: 1000ms
        # 重试次数 默认 3
        max-attempts: 3
        # 重试最大时间 默认 1000 ms
        max-interval: 1000ms
        # 重试的间隔乘数 （第一次1秒，第二次2秒，第三次4秒）
        multiplier: 1


mybatis-plus:
  #配置Mapper.xml映射文件
  mapper-locations: classpath*:/mapper/*Mapper.xml
  type-aliases-package: com.xxxx.seckill.pojo

logging:
  level:
    #扫描Mapper接口所在的包
    com.xxxx.seckill.mapper: debug
